### ISSUE TITLE
Airbrake improvement

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#100]
@D-ECHO please make the airbrakes come out as far as it's shown on page 6 in the manual: https://www.capmembers.com/media/cms/ASK21__Schleicher__Flight_Manual_0F12AEE54A4A2.pdf

The front of the airbrake is painted orange: http://rs231.pbsrc.com/albums/ee247/jetpack_photos/Revell%20Gliders/airbreak_zps1bacd991.jpg~c200

Not sure about the back, I'll try to check next time. Could well be the same colour.

**Comment by ghost** [comment]
![fgfs-screen-112](https://cloud.githubusercontent.com/assets/12275960/23959346/3a80487e-09a5-11e7-9275-a2945644755b.png)
Step 1

**Comment by viktorradnai** [comment]
Wow, this looks great! But it seems that the left airbrake is missing a support rod, it's only held by one.

**Comment by ghost** [comment]
Model part done in PR #107 
@gilbertohasnofb you wanna do the texture part (orange) or shall I?

**Comment by gilbertohasnofb** [comment]
> you wanna do the texture part (orange) or shall I?

I can do it if you would like. What about if I add an appropriate orange texture to the top right corner of `Models/blank-wings.png`? Also, do you have a reference how that should look like or should I just create a metallic orange texture?

**Comment by viktorradnai** [comment]
It's not shiny IIRC. It might be made of fibreglass as well.

**Comment by ghost** [comment]
@gilbertohasnofb in the texture repo I added the speedbrake uvmap to D-3981-wings.xcf, at this position you can paint it :D it should be the same for front and back

**Comment by gilbertohasnofb** [comment]
@D-ECHO that's great, thanks a lot! I am waiting for @viktorradnai 's pictures to see exactly how this should be done. Also, I am _very_ busy_ until Monday evening (job + PhD application), but I will get to this texture (as well as the bottom panel) very very soon.

**Comment by ghost** [comment]
No problem @gilbertohasnofb take your time, RL is always the most important! :D

**Comment by viktorradnai** [comment]
Hi, i've uploaded some pics to Google Drive. They were taken with a phone
in poor light so some are blurry but I hope they'll help. I was going to
take better ones today but the weather was so bad we didn't even fly. I'll
take more tomorrow if I can.

On 18 Mar 2017 16:41, "D-ECHO" <notifications@github.com> wrote:

No problem @gilbertohasnofb <https://github.com/gilbertohasnofb> take your
time, RL is always the most important! :D

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/viktorradnai/flightgear-ask21/issues/100#issuecomment-287558095>,
or mute the thread

**Comment by gilbertohasnofb** [comment]
@D-ECHO Great. I should be able to work on these on Monday or Tuesday
@viktorradnai excellent pictures, thanks a lot!

**Comment by viktorradnai** [comment]
@gilbertohasnofb @D-ECHO I have uploaded a few more pictures to Google Drive. They show some more detail such as the cable attachment points for the rudder (inside their fairing at the end of the tail), the trim adjusters, air vents, the area behind the instructor's head (above the wing main spar), the pitot tube inside the hole in the nose, etc. I have also taken pictures of complete gliders with an emphasis on trying to assess how shiny (or not) the surface looks when light shines on it from different angles. 

Warning: the last four cockpit images are an ASK23, not an ASK21. It looks quite similar.

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by D-ECHO** [comment]
@viktorradnai I can't find the image showing the pitot tube, where is it? ;)

**Comment by viktorradnai** [comment]
The photo needs to be manipulated to bring out detail in the shadow. I'll
try to do that later.

**Comment by ghost** [comment]
Yep I found it sry :D


Am 20.03.2017 um 14:25 schrieb Viktor Radnai:
> The photo needs to be manipulated to bring out detail in the shadow. I'll
> try to do that later.
>

**Comment by gilbertohasnofb** [comment]
Guys, tomorrow I will have some free time so I will take care of the bottom panel and airbrakes textures.

**Comment by gilbertohasnofb** [comment]
@D-ECHO In which branch did you make the modifications to the spoiler? I have seen that in the ASK21-textures repo you added the UV-map layer to the file `D-3981-wings.xcf`, but once I have the texture ready where should I push it to?

**Comment by ghost** [comment]
Branch newspoiler :D


Am 21.03.2017 um 18:39 schrieb Gilberto Agostinho:
