### ISSUE TITLE
Remake colour cubemap now that interior textures changed

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#103]
Recreate the colour cubemap using the new textures (the seat is no longer blue for instance). Also, it seems to me that the current one has the sides reversed, notice in the image below how the yellow and blue levers are reflected on the right-hand side of the glass instead of the left-hand side where they are located:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/23925737/ef10774a-0910-11e7-844e-1b31d8fd46b7.png)

**Comment by ghost** [comment]
will do once the interior texture is safe

**Comment by gilbertohasnofb** [comment]
@D-ECHO :+1: I think we are almost there. Once I get those stickers done I think the interior will be pretty much done, but let's see, no rush

**Comment by gilbertohasnofb** [comment]
@D-ECHO I think the interior textures are quite safe now

**Comment by ghost** [comment]
see #118

**Comment by gilbertohasnofb** [comment]
@D-ECHO can we close this?

**Comment by ghost** [comment]
IMO yes
