### ISSUE TITLE
Holes in the 3D model

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#106]
There are some holes in the 3D model, in particular close to the control surfaces. See:

![ask21-4 copy](https://cloud.githubusercontent.com/assets/5700795/23993527/3063806c-0a41-11e7-8a64-66111a126ed7.jpg)

![bug2](https://cloud.githubusercontent.com/assets/5700795/23993397/a902f9d6-0a40-11e7-8778-f5d773e78b47.jpg)

![bug3](https://cloud.githubusercontent.com/assets/5700795/23993395/a9014bea-0a40-11e7-8698-c93aaf968a3c.jpg)

![bug4](https://cloud.githubusercontent.com/assets/5700795/23993396/a9021886-0a40-11e7-980c-ccfeb8c94e28.jpg)

These above show the issues with the rudder and with the elevator, and I suspect the same should be happening with the ailerons, though I forgot to make screen shots of that.

**Comment by ghost** [comment]
rudder and elevator should be fixed in PR #107, aileron seems to be fine to me

**Comment by gilbertohasnofb** [comment]
@D-ECHO elevators and ailerons are looking fine, but the rudder still has some issues, see this image here:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/24023159/bd2a16aa-0aaa-11e7-8911-ffbae61ac66e.png)

Notice how at the very end of the fuselage, where it joins the rudder, there is still a circular hole

**Comment by ghost** [comment]
see #110 :D

**Comment by gilbertohasnofb** [comment]
Closed via #110
