### ISSUE TITLE
yaw string for instructor

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#121]
In [this video](https://www.youtube.com/watch?v=UkEuUn4E2Uw), the instructor also has the yaw string above his cockpit, isn't this missing in our plane? Something on this position:

![string](https://cloud.githubusercontent.com/assets/5700795/24415477/e4ef6ba0-13e1-11e7-9c9b-f7671c987e22.png)

If we add this, the default viewpoint of the instructor may need to change a bit as I don't think the string will be visible without either zooming out or repositioning the camera

**Comment by viktorradnai** [comment]
@gilbertohasnofb thanks for raising this. Yes, the instructor definitely has a yawstring, and yes, the instructor's view is definitely way too zoomed by default.

**Comment by gilbertohasnofb** [comment]
@D-ECHO thanks for adding this to the branch `newint` but I found a bug: the strings of are visible through solid objects, is there a way of fixing this? See:

![fgfs-screen-004](https://cloud.githubusercontent.com/assets/5700795/24422076/8f0863f6-13f8-11e7-9230-3ebfc211ec19.png)

**Comment by ghost** [comment]
It's actually hanging down in front of the objects, I'll try to fix

**Comment by ghost** [comment]
Should be fixed in 81870149eb427de88b60c2d6801d6effcb817490

**Comment by gilbertohasnofb** [comment]
Since `newint` is not yet merged, I would have suggested to leave this opened. If anything happens and that branch doesn't get merged, it becomes difficult to keep track of has been or needs to be done. But since this is already closed, we just keep it as it is now.

**Comment by ghost** [comment]
Good idea :D

**Comment by gilbertohasnofb** [comment]
But I confirm this has been fixed in that branch :+1:

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/viktorradnai/flightgear-ask21/pull/131
