### ISSUE TITLE
raise polycount for the hoop around cockpit

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#122]
@D-ECHO Perhaps we could raise the number of polys in the hoop visible from the instructor's view. As it is right now, it looks a bit too "chopped" to me. And we don't need to increase the polycount for the whole fuselage, just the hoop and the glass canopy would suffice

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/24415620/5c87aee8-13e2-11e7-8992-7f98a75d72dd.png)

What do you think?

**Comment by ghost** [comment]
You're right, but unfortunately that's not very easy to do...

**Comment by ghost** [comment]
I've increased it a bit.. what do you think? 
![fgfs-screen-126](https://cloud.githubusercontent.com/assets/12275960/24420597/b28a3d40-13f3-11e7-9ef3-e2302c9fd562.png)

**Comment by gilbertohasnofb** [comment]
Oh, this looks _so_ much better!! :clap:

**Comment by gilbertohasnofb** [comment]
The problem is that they sometimes fall to the other direction when not in flight, so I suspect that even with this increase they will be seen though solid parts. Also, the position might be too high now compared with the real cockpit

**Comment by gilbertohasnofb** [comment]
Please disregard my last comment
