### ISSUE TITLE
the animation of the pilot rudder pedals is buggy

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#123]
The animation of the pilot rudder pedals is buggy:

![fgfs-screen-005](https://cloud.githubusercontent.com/assets/5700795/24423610/dd903fe4-13fd-11e7-8dfd-a43737cdb4d4.png)

Or is this how it is supposed to look like?

**Comment by ghost** [comment]
Is by time fixed
