### ISSUE TITLE
Move instructor's hook placard a bit closer to handle

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#124]
Move instructor's hook placard a bit closer to handle

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/24423638/f8d9e426-13fd-11e7-9a00-7ba0474ed34d.png)

**Comment by ghost** [comment]
Fixed in fabf4a2fa864aed98c6eb9ce0a372625e4660a0a
