### ISSUE TITLE
Simulate tail "rattling" close to stall

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#128]

**Comment by viktorradnai** [comment]
How would you like to simulate this? I think this is mostly just felt in the stick but that would require force feedback.

**Comment by ghost** [comment]
IIRC, it's also feelable so maybe just some view up and down can help, but I'd need to test it IRL again, was over half a year ago

**Comment by viktorradnai** [comment]
I don't remember feeling my body shaking when we get buffeted. I just feel it as subtle rattling of the stick. But I need to test it too, to be sure.

**Comment by ghost** [comment]
Looking at videos of stalls it also doesn't seem as prominent as in my memory, will observe next time I stall in the '21

**Comment by ghost** [comment]
I'll close this for now
