### ISSUE TITLE
Aircraft list options

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#130]
On FGRun, I see two options for our aircraft here:
- ASK 21 Passenger/Instructor View
- Schleicher ASK 21 Glider

The second one works fine, the first one loads an "invisible" aircraft (i.e. no 3D model...). Do we need this first option or should we simply remove it?

*Correct Typo (D-ECHO)

**Comment by ghost** [comment]
Well, the passenger/instructor view is exactly what it says, you can sit on the passenger/instructor seat in the ASK21 via multiplayer :D

**Comment by viktorradnai** [comment]
I should point out that the manufacturer is Schleicher, not Schneider. It's trivial to fix but I don't want to push changes to someone else's working branch.

**Comment by ghost** [comment]
It's not a failure in the aircraft it's the failure in the issue message :D

**Comment by gilbertohasnofb** [comment]
Sorry guys but the current labelling is _extremely_ unclear. The very top option "ASK 21 Passenger/Instructor View" is not mentioning anything about multiplayer, and so it's very confusing for the user. Perhaps better would be:

-    Schleicher ASK 21 Glider
-    Schleicher ASK 21 Passenger/Instructor View for Multiplayer

**Comment by ghost** [comment]
see 60326eafbc947824f702ea0ed6b7605d39269960

**Comment by gilbertohasnofb** [comment]
Great!!

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/viktorradnai/flightgear-ask21/pull/131
