### ISSUE TITLE
Vents are one sided 3D models

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#133]
Vents are one sided 3D models and look transparent from outside:

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/25176384/40512e0c-24fe-11e7-850e-5d4701663db8.png)

**Comment by ghost** [comment]
Fixed in a8031975cbb021949ce2d7ab1552b980c4473233

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/viktorradnai/flightgear-ask21/pull/131
