### ISSUE TITLE
Problems with right wing mesh

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#134]
The right wing mesh has some problems at the point it connects with the fuselage (left wing is perfect). See:

![fgfs-screen-006](https://cloud.githubusercontent.com/assets/5700795/25176425/5e5ae1b8-24fe-11e7-9216-b9cfd3a48a4f.png)

Right wing:
![fgfs-screen-007](https://cloud.githubusercontent.com/assets/5700795/25176426/5e5c7096-24fe-11e7-8faf-9d695a05f12d.png)

Left wing (all ok!):
![fgfs-screen-008](https://cloud.githubusercontent.com/assets/5700795/25176427/5e5f717e-24fe-11e7-8373-3c51fa75e358.png)

**Comment by ghost** [comment]
confirmed

**Comment by ghost** [comment]
![fgfs-screen-264](https://cloud.githubusercontent.com/assets/12275960/25176910/29d37e62-2500-11e7-92c0-4c2b42063b47.png)
fixed

**Comment by gilbertohasnofb** [comment]
Great!

**Comment by ghost** [comment]
See 9d90ba2

**Comment by gilbertohasnofb** [comment]
Closed via https://github.com/viktorradnai/flightgear-ask21/pull/131
