### ISSUE TITLE
Model tail closer to reality

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#139]
I already got to this, need to tweak some more though
![screenshot_20171111_074524](https://user-images.githubusercontent.com/12275960/32687073-6f5fb38c-c6b4-11e7-9fe5-d3c0f42df990.png)

**Comment by ghost** [comment]
![screenshot_20171111_195323](https://user-images.githubusercontent.com/12275960/32692550-0c06988a-c71a-11e7-9ad3-d2f4903dfe12.png)
some further progress

**Comment by ghost** [comment]
![fgfs-screen-414](https://user-images.githubusercontent.com/12275960/32692773-947fab08-c71e-11e7-8b0a-f2e66a7277ce.png)
in fg

**Comment by gilbertohasnofb** [comment]
Very nice! :clap:

**Comment by ghost** [comment]
see #156

**Comment by viktorradnai** [comment]
Closed by #156
