### ISSUE TITLE
Reflection switch broken after Simulation Reset

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#14]
Hi, it looks like the window shader no longer works after the latest PR (not sure when it stopped working).

**Comment by ghost** [comment]
I'll have a look

**Comment by ghost** [comment]
Hm... works perfect for me here, are you sure you enabled it? ;)

**Comment by viktorradnai** [comment]
Actually you are right, the problem is  different. 

If you reset the simulation using Shift-Esc or File > Reset, the Enable / disable shader function stops working. If you have enabled it before reset, it will stay permanently enabled, if it was disabled it will stay disabled. If you restart Flightgear it works again. This may be Nasal issue or a Flightgear one, not sure.

**Comment by ghost** [comment]
As the window shader has nothing to do with nasal coding, it's probably a flightgear issue :(

**Comment by viktorradnai** [comment]
Is it just me or is the glass shader completely broken now?

**Comment by ghost** [comment]
Works perfect here..

**Comment by viktorradnai** [comment]
This seems to work now, not sure what has changed. Must be something to do with how Flightgear saves the state of properties.
