### ISSUE TITLE
Rudder texture regression

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#147]
A while ago, the rudder texture seems to have reverted back to its previous incorrect state (where the letter printed on the rudder is mirrored). According to git bisect, this has occurred with this commit: 

> commit 94b1450a357035b2d7d3b6683b1d8b77ed80e19d (HEAD, refs/bisect/bad)
> Author: D-ECHO <echoair@t-online.de>
> Date:   Tue Mar 28 20:25:30 2017 +0200

>     New interior (and fuselage) model!

**Comment by viktorradnai** [comment]
Note the problem on the tail: 

![image](https://user-images.githubusercontent.com/4738178/34343740-2431e2ea-e9d2-11e7-9775-f0e72f9b5f60.png)

**Comment by ghost** [comment]
I will push the new tail (with better fuselage-tail transition #139) once I'm back at my other computer, probably after new year, IIRC it has it fixed, so I'd put this issue on hold until then

**Comment by ghost** [comment]
see #156

**Comment by viktorradnai** [comment]
Closed by #156
