### ISSUE TITLE
Make airbrake extend less

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#148]
The airbrakes extend a bit too much on the model. In reality there isn't much of a gap between the bottom of the airbrake and the top of the wing even when the brake is fully deployed. Please change the animation so the airbrake only extends to about as much at 100% as it does now at about 50%.

![image](https://user-images.githubusercontent.com/4738178/34343877-aa5f0160-e9d5-11e7-8307-ee9b182fa3cf.png)

**Comment by ghost** [comment]
Absolutely correct, also noted this :D will fix

**Comment by ghost** [comment]
see #149
