### ISSUE TITLE
Improving engine operations by keyboard. 

### ISSUE THREAD

**Issue by WillyFG** [viktorradnai/flightgear-ask21#161]
As a pilot I want to fully control the engine by means of the computer's keyboard, so that I do not need to use the computer's mouse to click panel items (can be hard on small computer screens) OR so that I can permanently use the computer's mouse to control the stick, e.g. when cutting-off the engine while flying.

I order to achieve full keyboard control, it's required that ...

1. the starter button can be turned ON by pressing "s" on the keyboard
1. the engine-control-unit's (ECU's) main switch can be switched ON by pressing "}" and switched OFF by pressing "{"
1. the propeller brake can be applied / released by pressing some suitable keys (t.b.d.)

Using "{" / "}" to operate the ECU's main switch appears to be logical, because these keys are generally used in FG to operate the ignition system, which is under direct control of the ECU for the ASK 21 Mi (i.e. ECU:ON = ignition:BOTH and ECU:OFF = ignition:OFF).

**Comment by ghost** [comment]
should be fixed by #166
