### ISSUE TITLE
Multiplayer - model incorrect?

### ISSUE THREAD

**Issue by legoboyvdlp** [viktorradnai/flightgear-ask21#163]
![image](https://user-images.githubusercontent.com/10434911/45175515-8e7df480-b205-11e8-8cd2-5942f77f7c06.png)
Over multiplayer the tail boom is missing?

**Comment by ghost** [comment]
This is an incompatibility bug when the pilot flying has an older variant, so the viewed version does not know whether it is the -mi variant or not. In the jsb branch, this is fixed so the glider model is always visible when no data is transferred on this.
@legoboyvdlp

**Comment by ghost** [comment]
Will probably be fixed by #164
