### ISSUE TITLE
Version 5.0

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#165]
As we've done quite a lot of things (mostly JSB) since last FGAddon version 4.0, we might want to prepare for Version 5.0 release to FGAddon, I'm doing some FDM tweaks in the jsb branch atm, if we can merge those, then otherwise I'd be clear for a release, any bugs/issues that we need to address before?

**Comment by ghost** [comment]
@viktorradnai @gilbertohasnofb Any remarks/bugs before Version 5.0 for SVN?

**Comment by gilbertohasnofb** [comment]
if I have the chance, I will try to work on the texture issues, particularly the improvements to the interior. When are we thinking about releasing version 5.0?

**Comment by ghost** [comment]
I'd actually like to release it quite soon as the fgaddon version by now is really outdated

**Comment by gilbertohasnofb** [comment]
hmm in that case I think I won't be able to work on the textures, these next few weeks will be tough for me. But I think we should make a release soon then as not to have an out of date aircraft in FGAddon, and then we can work on new features in the future

**Comment by ghost** [comment]
Makes sense. In my opinion it would be best to just release the current master to fgaddon, in case noone has any complaints?

**Comment by gilbertohasnofb** [comment]
I agree

**Comment by ghost** [comment]
Okay :D
