### ISSUE TITLE
Further development

### ISSUE THREAD

**Issue by D-ECHO** [viktorradnai/flightgear-ask21#173]
Hi there, hi Viktor, hi Gilberto,

I'd like to restart some work on the ASK21, fixing some things, improving others and optimising for current FG.
As the repo has been pretty much quiet for the last >5 years, I wanted to ask beforehand, whether you're still interested in the development and whether you'd like work to continue here in the repo.
@viktorradnai @gilbertohasnofb 

Have a nice day!

**Comment by viktorradnai** [comment]
Hi @D-ECHO, I have not done anything with Flightgear in at least two years and unfortunately I don't see this changing soon. So you are welcome to make your repo the official one for the ASK21 if you prefer. I still have access to these gliders IRL so let me know if you need photos or description for anything. Thanks for keeping the aircraft updated!

Best,
Vik

**Comment by gilbertohasnofb** [comment]
Hi @D-ECHO, I hope you are well! It's great to hear you want to restart working on this aircraft. Unfortunately I'm on the same situation as Vik, I haven't been involved with FlightGear in a number of years and I'm afraid I won't be able to take part in this project. I hope you find some enthusiastic co-developers in the FlightGear community, and I'm wishing you all the best! Gilberto

**Comment by D-ECHO** [comment]
Hi you both :)
Thank you very much for your nice words!
I updated the aircraft in FGAddon/next and will continue to do so.
I hope you're having a good time and thank you soooo much for all the development until here :)
