### ISSUE TITLE
Separate cockpit and instrument panel models from aircraft model

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#19]
Request from Emmanuel Baranger, ASK21-MI author:

The model should be split into parts for maintainability, Something like this should work, seems like this is how it was done for other aircraft:

- The aircraft model should be in Models/ask21.xml
- The cockpit should be in Models/Interior/interior.xml
- The instrument panels should be Models/Interior/panel-front.xml and Models/Interior/panel-rear.xml
- Instruments can live under Models/Interior/Panel/Instruments

The same separation should be done for the .ac files as well.

**Comment by ghost** [comment]
will do this after PR #16 is closed and issue #17 solved

**Comment by ghost** [comment]
In PR #21 the interior is split from the main model, after this I can continue splitting instrument panels

**Comment by ghost** [comment]
Now Step 2 -> Instrument panels

**Comment by viktorradnai** [comment]
Excellent, thanks for this :)

Please also upper-case the instruments folder to become "Instruments" when you rename.

**Comment by ghost** [comment]
See PR #22

**Comment by ghost** [comment]
Done
