### ISSUE TITLE
Add ALS interior shadows

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#2]
Since we already have a colored cubemap, this shouldn't be hard to add, I will do this as soon as my current PR is merged

**Comment by viktorradnai** [comment]
There are some shadows visible already using ALS. Are those coming from the outside of the aircraft?

**Comment by ghost** [comment]
Really? Could you send a screenshot plz? Because I've never seen them

**Comment by ghost** [comment]
See pull request #4

**Comment by viktorradnai** [comment]
There were some minimal shadows in the front footwell. The new shadows look good but it looks like there aren't showing up the rear instrument panel.

**Comment by ghost** [comment]
@viktorradnai should be fixed in pull request #6

**Comment by ghost** [comment]
"There were some minimal shadows in the front footwell." -> These were probably the texture-baked ambient occlusion shadows :D
