### ISSUE TITLE
Aerotow hook position incorrect

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#24]
The aerotow cable currently goes to the tip of the nose, but on an ASK21 the nose hook is located halfway between the tip of the nose and the nose wheel. IIRC this used to be correct but somehow got lost when merging.

Also it seems that the end-force-{x,y,z} tags in ask21-set.xml are needed to make the forces have the correct origin (or at least the YASim properties did not seem to be set unless these tags were there).

**Comment by ghost** [comment]
Could you do this? ;)

**Comment by ghost** [comment]
I never knew the aerotow hook was not located inside the nose :open_mouth:

**Comment by viktorradnai** [comment]
It's difficult to see on this pic, but note the cable position: https://i.ytimg.com/vi/Oqx0NT6_7rg/maxresdefault.jpg

The only thing inside the hollow part of the nose on an ASK21 is the pitot tube, which sits right in the middle and a few cm inside.

I have fixed this with #25.

**Comment by ghost** [comment]
Yep this picture shows it very well, thanks for that :D

**Comment by ghost** [comment]
Sorry for opening :D
