### ISSUE TITLE
Add more liveries

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#34]
G-CWJD and G-CKEJ (London Gliding Club) are ready and waiting ;)
Any others to be done?

**Comment by ghost** [comment]
![fgfs-screen-161](https://cloud.githubusercontent.com/assets/12275960/21516389/00609dec-ccd8-11e6-9473-2dc27b8a308c.png)
![fgfs-screen-162](https://cloud.githubusercontent.com/assets/12275960/21516390/00633728-ccd8-11e6-9fe8-0dfbb6158c3e.png)
Sorry if the liveries aren't 100% exact/good, your club's painters did an extraordinary job! ;)

**Comment by viktorradnai** [comment]
Thanks for this! I'll play with the fonts, other than that they look pretty good to me :)
