### ISSUE TITLE
Glider internals sticking out on the side of the fuselage

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#38]
If pilots are enabled, the instructor's legs are partially sticking out of the side of the fuselage. Also he corner of the instrument panel or something similar sticks out a little bit as well.

![fgfs-screen-194](https://cloud.githubusercontent.com/assets/4738178/21577877/4acbd8fa-cf63-11e6-85a0-f199d8521c9b.png)
![fgfs-screen-195](https://cloud.githubusercontent.com/assets/4738178/21577878/4accd1ba-cf63-11e6-8f7e-2d26cf9ba6d9.png)

**Comment by ghost** [comment]
However it's done, something is always sticking out, either out of front seat or out of fuselage, I'll try to find a solution after Version 1.0

**Comment by ghost** [comment]
Meanwhile I made both pilots a bit smaller, not realistic but ok as a temporary fix

**Comment by viktorradnai** [comment]
How about deleting the feet from the model?

**Comment by ghost** [comment]
Nah, wouldn't be that realistic either, would it? :P


Am 31.12.2016 um 18:38 schrieb Viktor Radnai:
> How about deleting the feet from the model?
>

**Comment by viktorradnai** [comment]
I was thinking that this would be less obvious as the feet are pretty well
hidden by the instrument panel.

**Comment by ghost** [comment]
Well, also true :D I'll have a look

**Comment by viktorradnai** [comment]
Also please don't forget about the two corners of the instrument panel that stick out.

**Comment by ghost** [comment]
See PR #42

**Comment by viktorradnai** [comment]
Fixed by #42
