### ISSUE TITLE
We're online on SVN!

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#39]
See https://sourceforge.net/p/flightgear/fgaddon/2367/tree//trunk/Aircraft/ASK21/ and
https://forum.flightgear.org/viewtopic.php?f=4&t=31363#p302392

Happy new year @viktorradnai @HHS81 @D-ABBA

**Comment by viktorradnai** [comment]
Awesome, Happy New Year all! :) 

And big thank you to Benedikt for all the work he did on the model this holiday season :)

**Comment by ghost** [comment]
Thanks back I can only say! :D

**Comment by ghost** [comment]
If it's okay for you, I will push updates to svn fgaddon once every one or two months when we're in a stable state

**Comment by viktorradnai** [comment]
Should be fine, but I'd like to see #41 out soon enough to be included in FG 2017.1

**Comment by ghost** [comment]
#41 is out! ;D
