### ISSUE TITLE
Add glide computer

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#40]
Another great thing to do, but I have no idea how to :fearful:

**Comment by viktorradnai** [comment]
It's probably better to leave this out and let people run xcsoar
separately. The typical ASK21 instrument panel is fairly basic, at least
the club ones for sure.

If you'd like to get fancy then a battery voltage indicator and a G meter
for aerobatics could be added as well as a master switch and a separate
on-off switch for the turn indicator (which is usually switched off to save
battery).

**Comment by ghost** [comment]
Just discovered this great XCSoar thingy ;) thanks! So yep, let's let this run the user seperate and concentrate on more important things
