### ISSUE TITLE
Add trim handle

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#44]
see https://forum.flightgear.org/viewtopic.php?f=4&t=31363#p302600:

> The trim handle is not included in the model, and it doesn't seem like the plane reacts to changes to the trim from the joystick buttons that I have mapped to trim. Without the trim handle visible, it is a bit difficult to see if changing the trim produces any result in the model.

**Comment by viktorradnai** [comment]
The trim works. I used the HUD to verify the position in the past. I also
have a Saitek Aviator joystick with two throttle levers and I map the
second throttle to the trim, which is reasonably similar to the real thing.

The only annoying aspect of Flightgear's trim system is that it not only
changes the neutral position of the stick but the entire range. So if you
apply full back stick and full rearward trim then you get a lot more up
elevator than you get with the trim fully forward. Maybe we could clamp the
elevator output in the yasim config to compensate for this.

**Comment by ghost** [comment]
see https://sfg-singen.de/bilder/flugzeuge/ASK21_Cockpit_vorne_kl.jpg
http://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-002.jpg
http://www.alexander-schleicher.de/wp-content/uploads/2015/04/21-Mi-Cockpit-002.jpg
note though that the last image is from an ASK21-MI

**Comment by ghost** [comment]
See #65
