### ISSUE TITLE
Adjust glide-angle

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#47]
see https://forum.flightgear.org/viewtopic.php?f=4&t=31363#p302600
>The sink rate in normal flight is abnormally low. I have not tried to calculate it, but it should be somewhere just below 1 m/s.

This is probably caused because the yasim glide-angle is not as expected, so massive testing with different values will be required.

**Comment by viktorradnai** [comment]
Minimum sink for an ASK21 is about 0.5m/s. If we're lucky the manual might
have a polar curve.

**Comment by viktorradnai** [comment]
ASK21 polar curve is here: http://www.fsglider.de/p_pol_e.htm

The are a couple of different versions, I need to compare them to make sure
that the data is the same.

On 4 Jan 2017 09:53, "Viktor Radnai" <viktor.radnai@gmail.com> wrote:

Minimum sink for an ASK21 is about 0.5m/s. If we're lucky the manual might
have a polar curve.

**Comment by ghost** [comment]
So from the polar curve we should get a sink rate of 0.75 at 90 km/h, I will test this
[EDIT]I got 0.17m/s, so yes, it's far too good

**Comment by ghost** [comment]
Please try with 4.5 for cruise and 5 for approach, that worked quite well for me

**Comment by viktorradnai** [comment]
See #49

**Comment by ghost** [comment]
Fine now :D
