### ISSUE TITLE
Check mass&mass distribution

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#48]
see https://forum.flightgear.org/viewtopic.php?f=4&t=31363#p302600
>The stick gives a feeling of very quick reactions to input. Are the masses and/or their distribution correct in the flight model?

**Comment by viktorradnai** [comment]
Maybe #49 helps with this as well. Although I'm not clear if the original poster meant the ailerons, the elevator or both.

**Comment by ghost** [comment]
Mass&Mass distribution seems to be fine. This is one of those "feeling" things that you can't really tell, maybe it's because of the joystick, maybe it's the aircraft....
