### ISSUE TITLE
Add helijah's ASK21-MI

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#5]
http://helijah.free.fr/flightgear/hangar.htm

Things to consider:
-can't use same model
Workflow:
-Ask Helijah for permission
-Add files for ASK21-MI
-Remove duplicate files/adapt for minimal extra space

**Comment by D-ECHO** [comment]
Will be done after PR #22

**Comment by ghost** [comment]
Won't happen
