### ISSUE TITLE
Use instruments with imperial units for G-CJWD and G-CKEJ liveries

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#50]
I'd like to have a different instrument panel for G-CJWD and G-CKEJ that has an ASI in knots, an altimeter in feet with the air pressure in HPa and a variometer that is in knots as well. This is the British gliding standard and this is how the gliders are set up in real life. Perhaps we can model an US example as well and give it an altimeter that uses InHg and a vario with fpm.

**Comment by ghost** [comment]
see #52

**Comment by ghost** [comment]
Would you mind doing a kts variant of your excellent kmh texture?

**Comment by ghost** [comment]
also see #61

**Comment by ghost** [comment]
Variometer (Winter) -> done
Airspeed Indicator (Winter) -> not done
Altimeter -> not done

**Comment by viktorradnai** [comment]
This should be resolved by #69 as well.

**Comment by ghost** [comment]
The altimeter isn't that good yet, do you want to keep it?

**Comment by viktorradnai** [comment]
I would prefer to have a nicer one for imperial units, but didn't have time
to change the pressure setting disc to use mbar values instead of InHg. Is
this something you could do quickly?

**Comment by ghost** [comment]
I've tried altering this multiple times but I actually suck at it ;)


Am 05.02.2017 um 16:36 schrieb Viktor Radnai:
> I would prefer to have a nicer one for imperial units, but didn't have 
> time
> to change the pressure setting disc to use mbar values instead of InHg. Is
> this something you could do quickly?
>

**Comment by viktorradnai** [comment]
It's that kind of sport :) Tedious and annoying work :)

**Comment by viktorradnai** [comment]
You can draw a nearly complete circle in inkscape to measure angles then
copy and rotate the text object by that angle. If you have two on the
opposite side then rotating around the centre should be correct. When you
have two, group them together to make four, then copy that to make eight
and so on. Then finally you have to edit each number one by one... Not much
fun.

**Comment by ghost** [comment]
Let's do the alt texture for version 3.0 ;)

**Comment by ghost** [comment]
I'll close this, issue #61 will stay open for ft altimeter
