### ISSUE TITLE
Add G meter

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#51]
ASK21 aircraft to be used for aerobatics must be fitted with a G meter. I think we should add this to the panel.

**Comment by ghost** [comment]
Do you know whether there is already a modelled one anywhere in fg?

**Comment by viktorradnai** [comment]
Aircraft/Cap10C/Models/Interior/Panel/Instruments/ForceG2.png looks like a good start. If I can make it to the club I'll try to take some photos of an actual ASK21 installed instrument, to get the labelling correct.

**Comment by viktorradnai** [comment]
Closed by #52
