### ISSUE TITLE
Add canopy jettison handle on top of instrument panel

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#53]
See the image here, the canopy emergency release is the big lever with the red plastic on the end: https://i.ytimg.com/vi/-W6O3lX9rwE/maxresdefault.jpg

**Comment by viktorradnai** [comment]
https://i.ytimg.com/vi/-W6O3lX9rwE/maxresdefault.jpg

**Comment by ghost** [comment]
Ah, have always wondered what this is for ;)


Am 12.01.2017 um 04:47 schrieb Viktor Radnai:

**Comment by ghost** [comment]
I've implemented the handle and canopy front jettison. For the rear I did nothing yet because it is handled by pulling both normal open handles fully to the back.

**Comment by viktorradnai** [comment]
You are right. For the rear seat, the detachment of the canopy is handled by the airflow as far as I know :)

**Comment by ghost** [comment]
see #58
