### ISSUE TITLE
Retweak flight model for current version of YASim

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#55]
Apparently YASim has a lot of bugfixes that aren't enabled by default in order not to break already working models. This newsletter article has the details: http://wiki.flightgear.org/FlightGear_Newsletter_April_2014

I have tried to add YASIM_VERSION_CURRENT to the config but this made the YASim solver fail to get a solution. Therefore we'll need to tweak the flight model parameters to make the solver work, possibly even starting from scratch, and see if this gives more accurate results, particularly in conditions such as a mushing stall, with the nose high up.

This issue is a placeholder so I remember to do this eventually :)

**Comment by ghost** [comment]
To be done:
  - improve spoiler effectiveness
  - greater adverse yaw (close to zero at the moment)

**Comment by ghost** [comment]
With these values it seems to be rather realistic:
`
        <flap0 start="0.43" end="0.97" lift="1.3" drag="1.7"/>
        <spoiler start="0.34" end="0.44" lift="-4" drag="75.5"/>`

**Comment by ghost** [comment]
Anything to be done about this?

**Comment by viktorradnai** [comment]
Still in progress.

**Comment by HHS81** [comment]
https://forum.flightgear.org/viewtopic.php?f=4&t=31889

**Comment by viktorradnai** [comment]
Fixed by #138
