### ISSUE TITLE
Immat (or not)

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#59]
We still have a commented-out immat.nas flying around in our folder/set file. Personally I don't like to have immat support here, because IMO the special registration (and also it's color, text type etc.) belongs to the livery. What do you think of this?

**Comment by viktorradnai** [comment]
I think being able to set the callsign is important for multiplayer in particular. Ideally what I'd like would be to be able to change the livery and have the callsign displayed with the correct font for the livery. If this is not possible, then I'd rather not change the callsign.

**Comment by ghost** [comment]
It is possible to do so, though it would mean to create a png containing 
all letters/number for each font, IMO a bit of a waste of space (not ace 
of spades :P) Maybe it would be better to create a bunch of liveries 
with set callsign and some special ones which have white spaces so there 
is a possibility to chose callsign (with font=arial)


Am 27.01.2017 um 23:51 schrieb Viktor Radnai:
