### ISSUE TITLE
Better air cooler

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#62]
![whatsthis](https://cloud.githubusercontent.com/assets/12275960/22395577/d841191c-e542-11e6-923c-bed29ff33aab.jpg)
Image source http://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-002.jpg

**Comment by viktorradnai** [comment]
It's the cabin ventilation and pilot cooling system :) It's an air vent
that can be tilted upwards or backwards and can be opened or closed with a
butterfly valve in the flat part.

**Comment by ghost** [comment]
Ok thanks, maybe we can improve our model there a bit

**Comment by ghost** [comment]
see #65
