### ISSUE TITLE
Better seat texture

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#64]
At the moment we have a simple grey texture, maybe we can get a texture like this? 
![ASK21 Seat](http://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-002.jpg)

**Comment by viktorradnai** [comment]
Sure. Our cushions are just plain blue; I think either would look a lot
better but maybe a pain colour is easier to implement.

**Comment by ghost** [comment]
Yep, I'm trying to make a texture out of the images you send (hope they 
are GPL?)

Am 28.01.2017 um 12:02 schrieb Viktor Radnai:
> Sure. Our cushions are just plain blue; I think either would look a lot
> better but maybe a pain colour is easier to implement.
>

**Comment by viktorradnai** [comment]
Yes, consider them released under a licence that permits use or creation of
derivative works for Flightgear :)

**Comment by ghost** [comment]
Thx

**Comment by ghost** [comment]
![fgfs-screen-197](https://cloud.githubusercontent.com/assets/12275960/22396180/e807a5e0-e552-11e6-9db6-8cc54bd7ddfd.png)
Fine with this? I wanted to keep it simple :D

**Comment by viktorradnai** [comment]
Yes it's nice. But remember that the rear stick is embedded into the seat.
It pokes though a hole.

**Comment by ghost** [comment]
Is the rear stick completely straight?

**Comment by ghost** [comment]
(self-answering) No, it isn't. See ![Rear Cockpit](http://www.alexander-schleicher.de/wp-content/uploads/2015/03/21-Cockpit-005.jpg)

**Comment by viktorradnai** [comment]
My bad, it's acully the front seat that has the stick embedded.

**Comment by ghost** [comment]
Yes, now I know thx
