### ISSUE TITLE
Rework Aircraft Rating?

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#70]
In the -set file as well as on the wiki, we still have the following rating
**_FDM_**: 2: FDM tuned for cruise configuration.
**_Systems_**: 2: Working electrical system, fuel feed cockpit controls, stable autopilot
**_Cockpit_**: 2: 2D panel in 3D cockpit, or incomplete 3D panel
**_Model_**: 3: Accurate 3D model with animated control surfaces, gear detailing (retraction, rotation), prop
In my opinion this is not quite correct, e.g. **Cockpit** should IMO be improved to a 4 as we have
" 3D panel and accurately modelled 3D cockpit, plain texturing. Hotspots for majority of controls"
**Systems** should be corrected to 4 (note here that the ASK21 has very few systems to model). I have added a limit system which I will push after tooltips are solved. Later we can also add a bit more code to this so that e.g. the spoilers stuck/break if operated above 250km/h or that the wings brake under too heave load. Also, what I've thought of is to add fake spoilers to the wing connected to a rain property decreasing lift and increasing drag when flying in rain :D 
**Model** could be increased to 4: Accurate 3D model with animated control surfaces, gear, prop, livery support (if applicable). or maybe even 5 as we already have shader effects etc. but I think for a 5 we should improve the exterior model a bit further.
About the **FDM** I'm not sure how realistic it is.

**Comment by viktorradnai** [comment]
I agree, we can have 4 across the board at least.

**Comment by ghost** [comment]
see PR #72

**Comment by viktorradnai** [comment]
Closed by PR #72
