### ISSUE TITLE
Redo panel uvmap

### ISSUE THREAD

**Issue by ghost** [viktorradnai/flightgear-ask21#77]
Gilberto Agostinho contacted me some days ago and offered his help in improving textures. Therefor he suggested to redo the uvmap for the panel so to have it on one texture as it is done for the Interior/parts.png or the interior.png here: https://github.com/D-ECHO/ASW28/blob/master/Models/interior.png
If you are okay with this, I will correct it ;)

**Comment by viktorradnai** [comment]
I'm OK with this. I generally take your recommendations for 3D model-related subjects as I lack the experience.

**Comment by ghost** [comment]
Btw, could you add Gilberto as a collaborator to the repository? (@gilbertohasnofb)

**Comment by viktorradnai** [comment]
Hi, I've added @gilbertohasnofb as requested. Gilberto, welcome :)

**Comment by gilbertohasnofb** [comment]
@viktorradnai Hi Viktor, thanks for adding me! I will push the work I have so far to the `panelstub` branch :smile:

**Comment by gilbertohasnofb** [comment]
This is what I have so far:

![glider-0](https://cloud.githubusercontent.com/assets/5700795/23592574/5fbb665e-0203-11e7-845d-cc884a916e58.jpg)

![glider-1](https://cloud.githubusercontent.com/assets/5700795/23592576/5fbcdcaa-0203-11e7-989c-54329c781d11.jpg)

![glider-2](https://cloud.githubusercontent.com/assets/5700795/23592575/5fbc6112-0203-11e7-97d8-97bc534db3cd.jpg)

**Comment by gilbertohasnofb** [comment]
@D-ECHO please do a `git pull` on the `panelstub` before continuing with the UV map, ok? I just pushed my commits :tada:

**Comment by viktorradnai** [comment]
Guys, this is starting to look really nice. Although some of the instruments seem to be brighter than others when in a cloud shadow. But that would be the instrument's problem I guess.

**Comment by gilbertohasnofb** [comment]
Great to hear that!

**Comment by gilbertohasnofb** [comment]
By the way, I started working on the exterior textures as well. I have improved the wheel texture, improved a bit the livery `customcallsign-2.png` and I pushed a new livery D-5394 based on a real aircraft. 

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/23593232/60e55d7e-020c-11e7-988a-1a9d07baa299.png)

**Comment by viktorradnai** [comment]
Talking about the wheel, actually both the main and front wheels are too skinny. I'll raise an issue for that. Also at least LGC flies the gliders with the main wheel fairing removed, presumably so it doesn't get full of mud during a typical UK winter. But that might be too much of a bother to model.

**Comment by ghost** [comment]
Thanks for you tex work, @gilbertohasnofb it's great! :D I've corrected the uvmap for the airvent and the microphone :D 
@viktorradnai I think this is because of some instruments having fake instrument lighting to make them readable when the sun shines in

**Comment by gilbertohasnofb** [comment]
@D-ECHO thanks a lot for the quick fix! So I will add those two interior textures (mic and vent) and finish reworking the liveries tonight, then this will be ready to merge

**Comment by ghost** [comment]
Great! btw, @gilbertohasnofb in which time zone are you?

**Comment by gilbertohasnofb** [comment]
@D-ECHO I am in UTC +1 as I am currently living in Germany, but I am kind of a night owl :smile:

**Comment by ghost** [comment]
Hugh, in Germany? Though you were living somewhere in America based on your online time (~01:00 usually) :D

**Comment by gilbertohasnofb** [comment]
Heheh I am actually from Brazil but I have been living in Europe for almost a decade now. And I tend to work on FG rather at night indeed :smile: You are also in Germany, aren't you?

**Comment by ghost** [comment]
Yep, south-western Germany. I guess you're living in Berlin?

**Comment by gilbertohasnofb** [comment]
Actually I am also in the South-west as well, in Freiburg :smile: 

So the interior is basically done, see:

![fgfs-screen-001](https://cloud.githubusercontent.com/assets/5700795/23627124/b6a641a8-02af-11e7-8533-81d44c923336.png)

I am now finishing to improve the wheel and the liveries, I am pushing it very soon

**Comment by gilbertohasnofb** [comment]
@D-ECHO Ok, so there are only two things that still need to be done before we can merge this:

- add a 3D button to the back seat stick. When UV-mapping it, you don't need to add the contour to that layer in gimp, just simply map it to this region on top of the instructor's stick:

![screenshot from 2017-03-06 20 32 46](https://cloud.githubusercontent.com/assets/5700795/23629498/338feca2-02b8-11e7-8a69-e0e7ecdbb35c.png)

- the tips of the wing (bottom side) aren't matching in the uv-map, see image below (look at the red bits). Please do not change the mapping itself from the texture files, just simply adjust it in Blender if possible, ok? See:

![fgfs-screen-002](https://cloud.githubusercontent.com/assets/5700795/23629509/38dff094-02b8-11e7-82fe-8a7668a1dacf.png)

**Comment by gilbertohasnofb** [comment]
@D-ECHO once you have some time could you please take a look on these two small things above, so we can merge this branch? Once this work has been done here, I will move on to work on the textures of the ASW 28.

**Comment by ghost** [comment]
PushToTalk Rear added and wing uvmap corrected ;) see commit f94f868

**Comment by gilbertohasnofb** [comment]
@D-ECHO Looks really good, thanks for the fixes! I just pushed a new commit improving a bit the interior texture around the nose, and from my part this is ready to be merged. A PR is on its way.
