### ISSUE TITLE
Wheels are too thin

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#80]
Both the main and front wheels are too skinny compared to the real aircraft. I've found a good pic showing the ASK21 from the front and tried to take a similar screenshot:

![21-mi-bugrad-001](https://cloud.githubusercontent.com/assets/4738178/23593373/0dd13cf8-0206-11e7-8144-9c1fac81ef8f.jpg)
![fgfs-screen-236](https://cloud.githubusercontent.com/assets/4738178/23593372/08144968-0206-11e7-9745-b62dbadcdc82.png)

Also it's probably worth mentioning at least LGC flies the gliders with the main wheel fairing removed, presumably so it doesn't get full of mud during a typical UK winter. But that might be too much of a bother to model.

The photo also shows the nose hook in reasonable detail -- which made me realise that both hooks have disappeared from the aircraft texture at least in the panelstub branch.

**Comment by gilbertohasnofb** [comment]
@viktorradnai I actually don't know anything about 3D modelling :cry:

**Comment by viktorradnai** [comment]
@gilbertohasnofb LOL, me neither, I thought I'm the only one who doesn't :)

**Comment by gilbertohasnofb** [comment]
Yeah, I never had the energy to sit down and learn how to use Blender :smile:

**Comment by ghost** [comment]
Does anyone of you by chance know how thick it should be?

**Comment by ghost** [comment]
Btw, are you aware the image you posted is from the ASK21MI? (there the front wheel is steerable)

**Comment by ghost** [comment]
I have made the wheels a bit thicker and therefor also changed the fairings:
![fgfs-screen-216](https://cloud.githubusercontent.com/assets/12275960/23613698/cc3192e0-0280-11e7-8244-dccf66ca8175.png)
@gilbertohasnofb please make the texture for the wheels a bit bigger (add some grey around it) so we don't have these white glitches on it. However, very good tex thanks!
![fgfs-screen-215](https://cloud.githubusercontent.com/assets/12275960/23613724/e6682b60-0280-11e7-9837-c0de199ca986.png)

**Comment by viktorradnai** [comment]
According to the maintenance manual, the main wheel is a 4.00-4 and the nose wheel is a 5.00-5. These appear to be standard aircraft wheel sizes used for all kinds of aircraft (even business jets), and I'm not sure what dimensions the numbers refer to. I would guess that these are in inches and one number refers to the radius of something (maybe the rim) and the other one the thickness (maybe also the rim). 

I haven't got the time to google this right now but searching for "aircraft wheel 5.00 5" or "aircraft wheel 4.00 4" returns a bunch of aviation stores selling them so one is bound to have a document with some dimensions.

The main wheel looks a lot better now, but I think the nose wheel is a bit too skinny still.

**Comment by gilbertohasnofb** [comment]
> please make the texture for the wheels a bit bigger (add some grey around it) so we don't have these white glitches on it.

Sure, I will add it to the same branch `panelstab` in which I have been working, so that when that's merged and this is merged, then the result will be fixed. Is that fine with you?

**Comment by ghost** [comment]
Yep, this is good!

**Comment by gilbertohasnofb** [comment]
> please make the texture for the wheels a bit bigger (add some grey around it) so we don't have these white glitches on it.

fixed in `panelstab`

**Comment by viktorradnai** [comment]
Fixed by #82

**Comment by ghost** [comment]
Didn't you say the nose wheel should be thicker?

**Comment by gilbertohasnofb** [comment]
@D-ECHO @viktorradnai perhaps the confusion is from my message above saying "fixed in `panelstab`". I was referring solely to the texture fix that @D-ECHO asked me to make, not to the whole issue of remodelling the wheels.
