### ISSUE TITLE
Improvements to the interior

### ISSUE THREAD

**Issue by gilbertohasnofb** [viktorradnai/flightgear-ask21#99]
1) add hole (trim indicator) to the right side of the interior for both the pilot and instructor, see:

![cockpit](https://cloud.githubusercontent.com/assets/5700795/23918608/fb30f3a0-08f3-11e7-8f57-da6d79d73021.jpg)

![fgfs-screen-003](https://cloud.githubusercontent.com/assets/5700795/23918614/017cd56c-08f4-11e7-9e8f-bbb6e87f8d3b.png)

2) add stickers as 3D rectangles and create textures for them according to the POH, see p. 20 on https://www.capmembers.com/media/cms/ASK21__Schleicher__Flight_Manual_0F12AEE54A4A2.pdf

**Comment by viktorradnai** [comment]
That "hole" is a visual trim indicator. There is something moving in there when you move the trim, unless it's been removed. Since the trim lever's position is self-explanatory, our gliders generally do not have it any more.

**Comment by gilbertohasnofb** [comment]
@viktorradnai @D-ECHO Ok, so I updated the original description and we can improve the interior by carving that hole and adding the stickers all in one single issue

**Comment by ghost** [comment]
Pushed placard objects to #107 and uvmap to dev repo @gilbertohasnofb

**Comment by ghost** [comment]
Once placards and bottom panel textures are done I'm going to create new cubemaps and splash screens

**Comment by gilbertohasnofb** [comment]
That sounds good, but perhaps we need to carve those holes for the trim references before redoing the cubemaps. And do the shadow cubemaps need to be modified? I have manually altered them, so my modifications would be lost.

**Comment by ghost** [comment]
Nope I'll only change the colormaps :D

and well, I'll take care of the trim hole later :D


Am 21.03.2017 um 18:41 schrieb Gilberto Agostinho:

**Comment by gilbertohasnofb** [comment]
:+1:

**Comment by ghost** [comment]
So I guess we're now set with the texturing for the moment, I'll regenerate the color cubemaps tomorrow ;)

**Comment by gilbertohasnofb** [comment]
Placards done, so now it's just a matter of creating the trim reference holes.

**Comment by gilbertohasnofb** [comment]
@D-ECHO how are the modifications to `newint` branch doing? Have you tried applying the texture I made for the back side of the seats?

**Comment by ghost** [comment]
Errrrr... sorry will do now :D

**Comment by ghost** [comment]
Done ;)

**Comment by gilbertohasnofb** [comment]
@D-ECHO Looking really good! Is there still anything to be done in this branch or can we merge it now?

**Comment by ghost** [comment]
Well I can't think of anything to be done soon, so well, I think we can merge it... The rear pedals aren't yet 100% right but I currently can't figure out how to correct them

**Comment by gilbertohasnofb** [comment]
> Well I can't think of anything to be done soon, so well, I think we can merge it.

Sounds good to me!

> The rear pedals aren't yet 100% right but I currently can't figure out how to correct them

Perhaps @viktorradnai could shoot a video of the pedals moving next time he is flying the real thing? That could help.

**Comment by ghost** [comment]
Not really, I know how they work and so on, but I can't get the right space for them, it's a quite close thing pilot seat - pedals
